**1.1. Length of a vector**

In [8]:
import numpy as np
def compute_vector_length(vector):
    len_of_vector = np.linalg.norm(vector)

    return len_of_vector

**1.2. Dot product**

In [9]:
def compute_dot_product(vector1, vector2):
    result = np.dot(vector1, vector2)

    return result

**1.3. Multiplying a vector by a matrix**

In [10]:
def matrix_multi_vector(matrix, vector):
    result  = np.dot(matrix, vector)
    return result

In [11]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


**1.4. Multiplying a matrix by a matrix**

In [12]:
def matrix_multi_matrix(matrix1, matrix2):
    result = np.dot(matrix1, matrix2)

    return result

**1.5 Matrix inverse**

*Check square matrix*

In [13]:
def is_square_matrix(arr):
    # Check numpy array
    if not isinstance(arr, np.ndarray):
      return False
    
    # Check 2D matrix
    if arr.ndim != 2:
      return False
  
    # Check dimension of matrix, if rows = cols --> square matrix
    rows, cols = arr.shape
    return rows == cols

***1.5.1. Calculate determinant*** 

In [14]:
def compute_determinant(matrix):
    det = np.linalg.det(matrix)
    return det

***1.5.2. Check invertibility & compute matrix inverse***

In [15]:
matrix1 = [[-2, 6], [8, -4]]
matrix = np.array(matrix1)

In [16]:
compute_determinant(matrix)

-39.99999999999998

In [17]:
def inverse_matrix(matrix):
    if compute_determinant(matrix) == 0:
        print("This matrix is not invertible")
    else:
        result = np.linalg.inv(matrix)
        print(f"The inverse of the matrix is: {inverse}")
    return result

**2.1. Eigenvector and eigenvalue**

In [18]:
def compute_eigenvalues_eigenvectors(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues,eigenvectors

**3.1. Consine similarity**

In [19]:
from numpy import dot
from numpy.linalg import norm

def compute_cosine(v1, v2):
  cos_sim = compute_dot_product(v1,v2) / (compute_vector_length(v1)*compute_vector_length(v2))

  return cos_sim

**4. Background subtraction**

In [20]:
import cv2

In [21]:
bg1_image = cv2.imread('D:/Onedrive2024/OneDrive/1.0 DS & AI/AIO2024/AIO-Exercise/Module_02/Week_02/GreenBackground.png', 1)
ob_image = cv2.imread('D:/Onedrive2024/OneDrive/1.0 DS & AI/AIO2024/AIO-Exercise/Module_02/Week_02/Object.png', 1)
bg2_image = cv2.imread('D:/Onedrive2024/OneDrive/1.0 DS & AI/AIO2024/AIO-Exercise/Module_02/Week_02/NewBackground.jpg', 1)

In [32]:
IMAGE_SIZE = (678, 381)
bg1_image = cv2.resize(bg1_image, IMAGE_SIZE)
ob_image = cv2.resize(ob_image, IMAGE_SIZE)
bg2_image = cv2.resize(bg2_image, IMAGE_SIZE)

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


In [25]:
def compute_difference(bg_img, input_img):
    difference_three_channel = cv2.absdiff(bg_img, input_img)
    difference_single_channel = np.sum(difference_three_channel, axis=2) / 3.0
    difference_single_channel = difference_single_channel.astype('uint8')

    return difference_single_channel

In [26]:
difference_single_channel = compute_difference(bg1_image, ob_image)
cv2_imshow(difference_single_channel)

AxisError: axis 2 is out of bounds for array of dimension 0

In [27]:
def computeBinaryMask(difference_single_channel):
    difference_binary = np.where(difference_single_channel >= 15, 255, 0)
    difference_binary = np.stack((difference_binary,)*3, axis=-1)
    return difference_binary

In [28]:
binary_mask = computeBinaryMask(difference_single_channel)
cv2_imshow(binary_mask)

NameError: name 'difference_single_channel' is not defined

In [29]:
def replaceBackGround(bg1_image, bg2_image, ob_image):
    difference_single_channel = computeDifference(bg1_image,ob_image)
    binary_mask = computeBinaryMask(difference_single_channel)

    output = np.where(binary_mask==255, ob_image, bg2_image)

    return output

In [30]:
output = replaceBackGround(bg1_image, bg2_image, ob_image)

cv2_imshow(output)

NameError: name 'computeDifference' is not defined

**Question:**

***Q1:***

In [ ]:
vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result, 2))

23.28


***Q2:***

In [ ]:
v1 = np.array([0 , 1, -1, 2])
v2 = np.array([2 , 5, 1, 0])
result = compute_dot_product(v1 , v2)
print(round(result, 2))

4


***Q3:***

In [ ]:
x = np.array([[1, 2], [3, 4]])
k = np.array([1, 2])
print('result \n', x.dot(k))

result 
 [ 5 11]


***Q4:***

In [ ]:
x = np.array([[-1, 2], [3, -4]])
k = np.array([1, 2])
print('result \n', x@k)

result 
 [ 3 -5]


***Q5:***

In [ ]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


***Q6:***

In [ ]:
m1 = np.array ([[0, 1, 2], [2, -3, 1]])
m2 = np.array ([[1, -3] ,[6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


***Q7:***

In [ ]:
m1 = np.eye(3)
m2 = np.array ([[1, 1, 1] ,[2, 2, 2], [3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


***Q8:***

In [ ]:
m1 = np.eye (2)
m1 = np.reshape (m1, (-1, 4))[0]
m2 = np.array ([[1, 1, 1, 1] ,[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


***Q9:***

In [ ]:
m1 = np.array ([[1, 2], [3, 4]])
m1 = np.reshape (m1, (-1, 4) , "F")[0]
m2 = np.array ([[1, 1, 1, 1] ,[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[29 29 29 29]


***Q10:***

In [ ]:
m1 = np.array ([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

The inverse of the matrix is: [[0.1  0.15]
 [0.2  0.05]]
[[0.1  0.15]
 [0.2  0.05]]


***Q11:***

In [ ]:
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix )
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


***Q12:***

In [ ]:
x = np.array ([1, 2, 3, 4])
y = np.array ([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577
