#**Exercise 1**

In [8]:
# Softmax function
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        sum_of_the_elements = x_exp.sum(0, keepdims=True)
        return x_exp / sum_of_the_elements

data = torch.Tensor([1, 2, 3])
my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [9]:
new_data = torch.Tensor([1, 2, 300000000])
output = my_softmax(new_data)
output

tensor([0., 0., nan])

In [15]:
# Softmax stable function
import torch
import torch.nn as nn

class MySoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x - x_max.values)
        sum_of_the_elements = x_exp.sum(0, keepdims=True)
        return x_exp / sum_of_the_elements

data = torch.Tensor([1, 2, 3])
softmax_stable = MySoftmaxStable()
output = softmax_stable(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [13]:
new_data = torch.Tensor([1, 2, 300000000])
output = softmax_stable(new_data)
output

tensor([0., 0., 1.])